### ISSUE TITLE
API Call Fails If Streamer Doesn't Have 7tv Emotes When Using 7tv/all Service Call

### ISSUE THREAD

**Issue by imbedhead** [adiq/temotes#1]
May be an edge case, but if a streamer doesn't have 7tv emotes for their channel while making an API request including "7tv" (or using "all") for the service parameter, the request will result in a 502 error.  This can be replicated via the API request test found on https://adiq.stoplight.io/docs/temotes/b3A6MzI2NTc0MjI-get-channel-emotes using the following parameters:

Case #1:
channel: imbedhead
services: twitch
results: Response code 200, with an empty array
Case #2:
channel: imbedhead
services: bttv
results: Response code 200, with an empty array
Case #3:
channel: imbedhead
services: 7tv
results: Response code 502, no results
Case #4:
channel: imbedhead
services: all
results: Response code 502, no results

A better case could be using streamer "imaqtpie", who has twitch, bttv, and ffz emotes, but not 7tv emotes, causing the issue mentioned above.

Also wanted to say love the api! Exactly what I needed for my own little project.

**Comment by adiq** [comment]
Hey @imbedhead!
Thanks for the kind words.

I appreciate your detailed report and promise to look into this issue soon 😉

**Comment by adiq** [comment]
Issue fixed 🎉  If a user does not use any service, an empty array will be returned.
